import type { Bot, Context } from "grammy";
import { mkdirSync, writeFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { getDb, type DomainRow } from "../lib/db.js";
import { parseDomain } from "../lib/rdap.js";
import { fmtMoney } from "../lib/format.js";

function parts(ctx: Context): string[] {
  return (ctx.message?.text || "").split(/\s+/).slice(1);
}
function owner(ctx: Context): number {
  return ctx.from?.id ?? 0;
}

function landingDir(): string {
  const dir = process.env.LANDING_DIR || "./landings";
  mkdirSync(dir, { recursive: true });
  return dir;
}

function renderHtml(row: DomainRow, opts: { telegram?: string; email?: string; whatsapp?: string }): string {
  const name = row.name;
  const bin = row.bin ? fmtMoney(row.bin) : null;
  const tg = opts.telegram || process.env.LANDING_TELEGRAM || "";
  const email = opts.email || process.env.LANDING_EMAIL || "";
  const wa = opts.whatsapp || process.env.LANDING_WHATSAPP || "";
  const ctas: string[] = [];
  if (bin) ctas.push(`<a class="btn primary" href="${tg ? `https://t.me/${tg.replace(/^@/, "")}` : "#inquiry"}">Buy now — ${bin}</a>`);
  ctas.push(`<a class="btn" href="#inquiry">Make an offer</a>`);
  const channels: string[] = [];
  if (tg) channels.push(`<a href="https://t.me/${tg.replace(/^@/, "")}">Telegram ${tg}</a>`);
  if (email) channels.push(`<a href="mailto:${email}?subject=Inquiry: ${name}">Email ${email}</a>`);
  if (wa) channels.push(`<a href="https://wa.me/${wa.replace(/\D/g, "")}?text=Inquiry%20about%20${encodeURIComponent(name)}">WhatsApp ${wa}</a>`);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${name} — for sale</title>
<meta name="description" content="${name} is available for acquisition.">
<meta property="og:title" content="${name} is for sale">
<meta property="og:description" content="Premium domain ${name} — available now.">
<style>
:root { color-scheme: light dark; --fg: #111; --bg: #fff; --muted: #666; --accent: #0066ff; }
@media (prefers-color-scheme: dark) { :root { --fg: #f5f5f5; --bg: #0a0a0a; --muted: #999; } }
* { box-sizing: border-box; }
body { font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif; color: var(--fg); background: var(--bg); margin: 0; }
.wrap { max-width: 640px; margin: 0 auto; padding: 80px 24px; }
h1 { font-size: clamp(2.5rem, 8vw, 4rem); margin: 0 0 8px; letter-spacing: -0.02em; }
p.lede { color: var(--muted); font-size: 1.1rem; margin: 0 0 32px; }
.btn { display: inline-block; padding: 14px 24px; margin: 6px 8px 6px 0; border-radius: 8px; border: 1px solid currentColor; color: var(--fg); text-decoration: none; font-weight: 500; }
.btn.primary { background: var(--accent); color: white; border-color: var(--accent); }
.btn:hover { opacity: 0.85; }
.channels { margin-top: 48px; padding-top: 32px; border-top: 1px solid rgba(127,127,127,.2); }
.channels a { display: block; padding: 8px 0; color: var(--fg); }
form { margin-top: 24px; }
input, textarea { width: 100%; padding: 12px; margin: 6px 0; border: 1px solid rgba(127,127,127,.3); border-radius: 6px; background: transparent; color: var(--fg); font: inherit; }
footer { margin-top: 64px; color: var(--muted); font-size: 0.85rem; }
</style>
</head>
<body>
<main class="wrap">
  <h1>${name}</h1>
  <p class="lede">This domain is available for acquisition.</p>
  <div>${ctas.join("")}</div>
  <section class="channels" id="inquiry">
    <h3>Contact</h3>
    ${channels.join("\n    ") || "<p>No contact channel configured.</p>"}
    <form action="mailto:${email}" method="post" enctype="text/plain">
      <input type="text" name="from" placeholder="Your name">
      <input type="email" name="email" placeholder="Your email" required>
      <input type="number" name="offer" placeholder="Offer (USD)">
      <textarea name="message" rows="3" placeholder="Message"></textarea>
      <button class="btn primary" type="submit">Send inquiry</button>
    </form>
  </section>
  <footer>Generated by domain.</footer>
</main>
</body>
</html>`;
}

function getDomain(name: string, ownerId: number): DomainRow | undefined {
  return getDb()
    .prepare("SELECT * FROM domains WHERE name = ? AND owner_id = ?")
    .get(name, ownerId) as DomainRow | undefined;
}

export function register(bot: Bot) {
  bot.command("landing", async (ctx) => {
    const ps = parts(ctx);
    const name = ps.find((p) => !p.startsWith("--"));
    const d = parseDomain(name || "");
    if (!d) return ctx.reply("Usage: /landing <domain> [--tg=user] [--email=foo@bar] [--wa=+62…]");
    const row = getDomain(d, owner(ctx));
    if (!row) return ctx.reply(`${d} not in portfolio.`);
    const flag = (k: string) => ps.find((p) => p.startsWith(`--${k}=`))?.split("=").slice(1).join("=");
    const html = renderHtml(row, { telegram: flag("tg"), email: flag("email"), whatsapp: flag("wa") });
    const path = join(landingDir(), `${d}.html`);
    writeFileSync(path, html, "utf8");
    const { InputFile } = await import("grammy");
    return ctx.replyWithDocument(new InputFile(Buffer.from(html, "utf8"), `${d}.html`), {
      caption: `Landing for ${d} generated.\nSaved: ${path}`,
    });
  });

  bot.command("publish", async (ctx) => {
    const [name] = parts(ctx);
    const d = parseDomain(name || "");
    if (!d) return ctx.reply("Usage: /publish <domain>");
    const row = getDomain(d, owner(ctx));
    if (!row) return ctx.reply(`${d} not in portfolio.`);
    const html = renderHtml(row, {});
    const path = join(landingDir(), `${d}.html`);
    writeFileSync(path, html, "utf8");
    getDb().prepare("UPDATE domains SET status='for_sale' WHERE name=? AND owner_id=?").run(d, owner(ctx));
    const baseUrl = process.env.LANDING_BASE_URL || "";
    return ctx.reply(
      `Published ${d} → ${path}${baseUrl ? `\nServe via: ${baseUrl}/${d}.html` : "\nServe ./landings/ with any static host (nginx / Caddy / GH Pages)."}`,
    );
  });

  bot.command("unpublish", async (ctx) => {
    const [name] = parts(ctx);
    const d = parseDomain(name || "");
    if (!d) return ctx.reply("Usage: /unpublish <domain>");
    try {
      unlinkSync(join(landingDir(), `${d}.html`));
    } catch {
      /* missing is fine */
    }
    return ctx.reply(`Unpublished ${d}.`);
  });
}
